blog/urls.py
from django.urls import path
from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogListView, BlogDetailVew, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('create/', BlogCreateView.as_view(), name='create'),
    path('', BlogListView.as_view(), name='list'),
    path('update/<int:pk>/', BlogUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='delete'),
    path('view/<int:pk>/', BlogDetailVew.as_view(), name='view'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='main')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models


NULLABLE = {'blank': True, 'null': True}


# Create your models here.
class Blog(models.Model):
    title = models.CharField(max_length=150, verbose_name='Заголовок')
    slug = models.CharField(max_length=150, verbose_name='slug', **NULLABLE)
    content = models.TextField(verbose_name='Cодержимое')
    preview_image = models.ImageField(upload_to='blog/', verbose_name='Изображение(превью)', **NULLABLE)
    created_at = models.DateField(auto_now_add=True, verbose_name='Дата создания')
    published = models.BooleanField(default=True, verbose_name='Опубликовано')
    views_count = models.IntegerField(default=0, verbose_name='Количество просмотров')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

blog/views.py
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView
from blog.models import Blog
from django.urls import reverse_lazy, reverse
from pytils.translit import slugify

# Create your views here.


class BlogCreateView(CreateView):
    model = Blog
    fields = ('title', 'content', 'preview_image')
    success_url = reverse_lazy('blog:list')

    def form_valid(self, form):
        if form.is_valid():
            new_article = form.save()
            new_article.slug = slugify(new_article.title)
            new_article.save()

        return super().form_valid(form)


class BlogUpdateView(UpdateView):
    model = Blog
    fields = ('title', 'content', 'preview_image')

    def form_valid(self, form):
        if form.is_valid():
            new_article = form.save()
            new_article.slug = slugify(new_article.title)
            new_article.save()

        return super().form_valid(form)

    def get_success_url(self):
        return reverse('blog:view', args=[self.kwargs.get('pk')])


class BlogDeleteView(DeleteView):
    model = Blog
    success_url = reverse_lazy('blog:list')


class BlogListView(ListView):
    model = Blog

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(published=True)
        return queryset


class BlogDetailVew(DetailView):
    model = Blog

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save()
        return self.object

blog/templates/blog/blog_confirm_delete.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="col-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Хотите удалить запись {{object.title}}</h4>
                </div>
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-danger">Подтвердить</button>
                        <a href="{% url 'blog:list' %}" type="button" class="btn btn-warning">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
{% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'catalog/base.html' %}
{% load image_view %}
{% block content%}
    <div class="card-body">
        <h1 class="card-title pricing-card-title">{{ object.title }} - {{ object.slug }}</h1>
        <img class="card-img-top" src="{% media_filter object.preview_image %}" style="width: 50px;">
        <div class="card-body">
            <p>
                {{ object.content }}
            </p>
        </div>
            <ul>
                <li>Дата создания: {{ object.created_at }}</li>
                <li>Просмотры: {{ object.views_count }}</li>
            </ul>
    </div>
{% endblock %}

blog/templates/blog/blog_form.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="col-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {{form.as_p}}
                        {% csrf_token %}
                        <button type="submit" class="btn btn-success  ">
                            {% if object %}
                                Сохранить
                            {% else %}
                                Создать
                            {% endif %}
                        </button>
                    </form>
                </div>
            </div>
        </div>
{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'catalog/base.html' %}

{% block content%}
<div class="col-12 mb-5">
    <a class="btn btn-outline-primary" href="{% url 'blog:create' %}">Добавить запись</a>
</div>
{% for object in object_list %}
<div class="col-md-4">
    <div class="card mb-4 box-shadow">
        <div class="card-body">
            <p class="card-text">{{ object|title }}</p>
            <p class="card-text">{{ object.description }}</p>
            <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                    <a href="{% url 'blog:view' object.pk %}" type="button" class="btn btn-lg btn-block btn-outline-primary">Подробнее</a>
                </div>
                <div class="btn-group">
                    <a href="{% url 'blog:update' object.pk %}" type="button" class="btn btn-lg btn-block btn-outline-primary">Update</a>
                </div>
                <div class="btn-group">
                    <a href="{% url 'blog:delete' object.pk %}" type="button" class="btn btn-lg btn-block btn-outline-primary">Delete</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endfor %}

{% endblock %}