blog/urls.py
from django.urls import path
from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogListView, BlogDetailVew, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('create/', BlogCreateView.as_view(), name='create'),
    path('', BlogListView.as_view(), name='list'),
    path('update/<int:pk>/', BlogUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='delete'),
    path('view/<int:pk>/', BlogDetailVew.as_view(), name='view'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='main')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from users.apps import UsersConfig
from users.views import RegisterView, ProfileView, CustomLoginView, PasswordRecoveryView, email_verification

app_name = UsersConfig.name

urlpatterns = [
    path('', CustomLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('email-confirm/<str:token>/', email_verification, name='email-confirm'),
    path('password_recovery/', PasswordRecoveryView.as_view(), name='password_recovery')
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

NULLABLE = {'blank': True, 'null': True}


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name='почта')
    avatar = models.ImageField(upload_to='users/', verbose_name='аватар', **NULLABLE)
    phone = models.CharField(max_length=35, verbose_name='номер телефона', **NULLABLE)
    country = models.CharField(max_length=35, verbose_name='страна', **NULLABLE)
    token = models.CharField(max_length=100, verbose_name='токен', **NULLABLE)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

users/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, PasswordResetForm
from users.models import User
from django import forms
from catalog.forms import StyleMixin


class UserRegisterForm(StyleMixin, UserCreationForm):

    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')


class UserProfileForm(StyleMixin, UserChangeForm):

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'avatar', 'country')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['password'].widget = forms.HiddenInput()


class PasswordRecoveryForm(StyleMixin, PasswordResetForm):

    class Meta:
        model = User
        fields = '__all__'

users/views.py
import secrets

from django.core.mail import send_mail
from django.shortcuts import get_object_or_404, redirect
from django.views.generic import CreateView, UpdateView, TemplateView
from django.contrib.auth.views import LoginView
from users.models import User
from users.forms import UserRegisterForm, UserProfileForm, PasswordRecoveryForm
from django.urls import reverse_lazy
from config.settings import EMAIL_HOST_USER


class RegisterView(CreateView):
    model = User
    form_class = UserRegisterForm
    template_name = 'users/register.html'
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):
        user = form.save()
        user.is_active = False
        token = secrets.token_hex(16)
        user.token = token
        user.save()
        host = self.request.get_host()
        url = f'http://{host}/users/email-confirm/{token}/'
        send_mail(
            subject="Подтверждение почты",
            message=f"Перейдите по ссылке для подтверждения почты {url}",
            from_email=EMAIL_HOST_USER,
            recipient_list=[user.email]
        )
        return super().form_valid(form)


def email_verification(request, token):
    user = get_object_or_404(User, token=token)
    user.is_active = True
    user.save()
    return redirect(reverse_lazy("users:login"))


class ProfileView(UpdateView):
    model = User
    form_class = UserProfileForm
    success_url = reverse_lazy('users:profile')

    def get_object(self, queryset=None):
        return self.request.user


class CustomLoginView(LoginView):
    template_name = 'users/login.html'

    def get_success_url(self):
        return super().get_success_url()


class PasswordRecoveryView(TemplateView):
    model = User
    template_name = 'users/password_recovery_form.html'
    form_class = PasswordRecoveryForm
    success_url = reverse_lazy('users:login')

    code = secrets.token_hex(8)

    def post(self, request, *args, **kwargs):
        email = request.POST.get('email')
        user = User.objects.get(email=email)
        code = self.code
        user.set_password(code)
        user.save()

        send_mail(
            'Восстановление пароля',
            f'Ваш новый пароль {code}',
            EMAIL_HOST_USER,
            [user.email],
        )
        return redirect(reverse_lazy("users:login"))

users/templates/users/login.html
{% extends 'catalog/base.html'%}

{% block content %}
<div class="col-12">
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                        Вход
                    </h3>
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">Войти</button>
                    <a class="p-l-2 btn btn-primary" href="{% url 'users:password_recovery' %}">Забыли пароль?</a>
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

users/templates/users/password_recovery_form.html
{% extends 'catalog/base.html'%}

{% block content %}
<div class="col-12">
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                        Восстановление пароля
                    </h3>
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    <label class="form-label">Email</label>
                    <input type="email" name="email" class="form-control">
                    <button type="submit" class="btn btn-success">Отправить новый пароль</button>
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

users/templates/users/register.html
{% extends 'catalog/base.html'%}

{% block content %}
<div class="col-12">
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                        Регистрация
                    </h3>
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">Зарегистрироваться</button>
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

users/templates/users/user_form.html
{% extends 'catalog/base.html'%}

{% block content %}
<div class="col-12">
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                        Профиль
                    </h3>
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">Сохранить</button>
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}